apiVersion: v1
kind: Template
metadata:
  name: adt-instituciones-api-config-template
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: adt-instituciones-api
